query (
  $filter: String
  $skip: Int
  $take: Int
  $relations: [AccountRelation!]
) {
  accounts(filter: $filter, skip: $skip, take: $take, relations: $relations) {
    id
    name
    createdAt
  }
}
