query ($id: ID!, $relations: [TransactionRelation!]) {
  transaction(id: $id, relations: $relations) {
    id
    accountId
    categoryId
    reference
    amount
    currency
    date

    account {
      id
      name
    }

    category {
      id
      name
      color
    }
  }
}
